### ISSUE TITLE
The drop-down box（mesh color by） only displays part of the content in the array dataset_arrays in 04_application/solution.py

### ISSUE THREAD

**Issue by qlhai** [Kitware/trame-tutorial#2]
Hi, I have some issue when I  run the 04_application/solution.py.  I replace the disk_out_ref.vtu,  and  I get a new dataset_arrays from my vtu file. The length of  my dataset_arrays is 14.  And the drop-down box only display 5 items. 

web page 
![image](https://github.com/Kitware/trame-tutorial/assets/28900893/a0390ad3-9399-4fa2-b87d-8decbd342994)

dataset_array 
![image](https://github.com/Kitware/trame-tutorial/assets/28900893/01bd9cf3-ab06-4cf6-820e-bf6e7c8692cd)

How can I fix it to display 14 items in dropdown box? 
Thanks!

**Comment by jourdain** [comment]
That's because you don't have a unique value for each entry. So from what I see from your data, you only have 5 entry in the drop down (0, 1, 2, 3, 4).
