### ISSUE TITLE
Web socket connection error for ParaView tutorial 

### ISSUE THREAD

**Issue by ghost** [Kitware/trame-tutorial#3]
Hello, I'm working on the Trame tutorials. The Paraview tutorial on the Trame page (https://kitware.github.io/trame/guide/tutorial/paraview.html) didn't work on my end. It shows connection closed with an error " WebSocket connection to 'ws://localhost:8080/ws' failed: Could not decode a text frame as UTF-8.

![connection closed](https://github.com/Kitware/trame-tutorial/assets/93155074/51727a9e-f281-4e96-a65b-c00c0bf4e1d9)

**Comment by jourdain** [comment]
Does any example work? Also, what OS/browser? Any other additional information you could provide to help reproduce the issue?

**Comment by ghost** [comment]
All other examples works except the ParaView ones. I'm using Windows 10 system. I've tried on Chrome, FireFox, and Microsoft Edge browsers and it's all showing the same error.

**Comment by jourdain** [comment]
Not sure if related but we are seeing issue with `aiohttp==3.9.0`. Can you try fixing its version to 3.8.6?

**Comment by ghost** [comment]
Appreciate your help :)  I switched to version 3.8.6 and it still shows that error.

![image](https://github.com/Kitware/trame-tutorial/assets/93155074/b81fbbd0-9959-476c-8739-d3b66edd1b2d)

**Comment by jourdain** [comment]
Are you using conda or the ParaView you can download on paraview.org/download?

**Comment by ghost** [comment]
For the ParaView tutorial, here are the steps I used.

1. Downloaded ParaView 5.12 RC1Windows Python3.10 msvc2017 AMD64.msi and installed it
2. Created a new conda environment pv-env and installed all libraries 
3. Ran the SimpleCone example with this command in Anaconda prompt
     /Applications/ParaView-5.10.1.app/Contents/bin/pvpython \
         ./05_paraview/SimpleCone.py  \
         --venv .pvenv
 4. A browser page automatically starts but shows connection closed

**Comment by jourdain** [comment]
Can you list what you mean by "all libraries".

Also did you try ParaView 5.11 with a venv (Python 3.9) instead of conda?

**Comment by ghost** [comment]
I downloaded ParaView 5.11 and changed to Python version 3.9 and it worked. I was using Python 3.12 before. Thanks for your help. Appreciate it.

**Comment by jourdain** [comment]
So, it was a Python miss match. Thanks for reporting back.
